In [1]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression
import matplotlib.pyplot as plt
%matplotlib inline
import warnings
warnings.filterwarnings("ignore", category=FutureWarning)
warnings.filterwarnings("ignore")

In [2]:
df = pd.read_csv("homeprices.csv")
df.head()

area   price
0  2600  550000
1  3000  565000
2  3200  610000
3  3600  680000
4  4000  725000

In [3]:
lr = LinearRegression()
lr.fit(df[['area']],df.price)

LinearRegression()

In [4]:
lr.coef_

array([135.78767123])

In [5]:
lr.intercept_

180616.43835616432

In [6]:
lr.predict([[5000]])

array([859554.79452055])

Save Model To a File Using Python Pickle

In [10]:
import pickle

In [11]:
with open("model_pickle","wb")as file:
    pickle.dump(lr,file)

In [12]:
# load file

In [13]:
with open('model_pickle','rb') as file:
    mp = pickle.load(file)

In [16]:
#create a sample using json
import json

samplejson1 = {
    "name":"luminar",
    "place":"kochi",
    "phno":"8387492345"
    
}
json_object=json.dumps(samplejson1)

In [17]:
json_object

'{"name": "luminar", "place": "kochi", "phno": "8387492345"}'

In [18]:
with open("sample.json","w")as file:
    file.write(json_object)

In [21]:
with open("sample.json","r")as file:
    new=json.load(file)

In [22]:
new

{'name': 'luminar', 'place': 'kochi', 'phno': '8387492345'}

Save Trained Model Using joblib

In [23]:
import joblib

In [24]:
joblib.dump(lr,"model_joblib1")

['model_joblib1']

Load Saved Model¶

In [25]:
mj=joblib.load("model_joblib1")

In [26]:
mj.coef_

array([135.78767123])